TimeMixing実装
Geson-anko/RWKV-ReImpl pull request #10
Opened 2023-04-29 06:18 UTC by myxyy

## 概要

TimeMixingの実装

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を `pytest`または `make test`コマンドでローカルにテストしましたか?
- [x] `pre-commit run -a` または`make format`コマンドで `pre-commit` フックを実行しましたか?

2023-04-29 07:03 UTC, myxyy commented
@Geson-anko 
https://github.com/Geson-anko/RWKV-ReImpl/pull/9 の議論を踏まえて重みを削除しました

2023-04-29 08:17 UTC, myxyy commented
> @Geson-anko #9 の議論を踏まえて重みを削除しました
@Geson-anko 
すみません、解釈を迷っていて、TimeMixingには出力に線形層があるようなのですがこれは残した方がよさそうでしょうか？

2023-04-29 10:03 UTC, Geson-anko commented
> @Geson-anko すみません、解釈を迷っていて、TimeMixingには出力に線形層があるようなのですがこれは残した方がよさそうでしょうか？

@myxyy TimeMixingレイヤーに線形層をいれてください。RWKVの実装に従います。
`PreviousMixing`レイヤーは、`x * mix_x + last_x * (1-mix_x)`を**自分たちの解釈で勝手に**モジュール化してできたレイヤーなので、設計の都合上、独立性が必要です。そうでない場合は、元の実装に従います。

2023-04-29 15:43 UTC, myxyy commented
@Geson-anko 
線形層取り消したのを取り消しました

2023-04-30 04:37 UTC, Geson-anko commented on src/models/components/time_mixing.py
> +        r = self.p_mix_r(x)
線形層忘れてます。
```suggestion
        self.p_mix_k = PreviousMixing(dim)
        self.p_mix_v = PreviousMixing(dim)
        self.p_mix_r = PreviousMixing(dim)
        self.Wk = nn.Linear(dim)
        self.Wv = nn.Linear(dim)
        self.Wr = nn.Linear(dim)
        self.numerator_last = None
        self.denominator_last = None
        self.W_out = nn.Linear(dim, dim, bias=False)
        self.w = nn.Parameter(torch.rand(dim))
        self.u = nn.Parameter(torch.rand(dim))
        self.sigmoid = nn.Sigmoid()

    # (len, batch, dim) -> (len, batch, dim)
    def forward(self, x: Tensor) -> Tensor:
        if self.numerator_last is None:
            self.numerator_last = torch.zeros(
                x.shape[1:], dtype=x.dtype, device=x.device
            )  # (batch, dim)
        if self.denominator_last is None:
            self.denominator_last = torch.zeros(
                x.shape[1:], dtype=x.dtype, device=x.device
            )  # (batch, dim)
        len = x.shape[0]
        k = self.Wk(self.p_mix_k(x))
        v = self.Wv(self.p_mix_v(x))
        r = self.Wr(self.p_mix_r(x))
```

2023-04-30 04:43 UTC, myxyy commented
@Geson-anko 
すみませんPreviousMixingの線形層見落としてました  
修正しました https://github.com/Geson-anko/RWKV-ReImpl/pull/10/commits/5d0935f70405dc27aecd7025ddd244ae4be024c4

2023-04-30 05:05 UTC, Geson-anko commented on src/models/components/time_mixing.py
> +        self.denominator_last = None
@myxyy p_mix_*のclear_hiddenよび忘れてます。

2023-04-30 05:24 UTC, myxyy commented on src/models/components/time_mixing.py
> +        self.denominator_last = None
修正しました https://github.com/Geson-anko/RWKV-ReImpl/pull/10/commits/a19cd3a1665dcdfbfcb4f86f57818404e40f0f1b

2023-04-30 05:58 UTC, Geson-anko requested changes
@myxyy 若干の修正をお願いします。

2023-04-30 05:58 UTC, Geson-anko commented on src/models/components/time_mixing.py
> +        fft_exp_k_v = torch.fft.rfft(exp_k_v, n=len * 2, dim=0)  # (?, batch, dim)
? = len + 1です。ナイキスト周波数より。
```suggestion
        fft_exp_w_progression = torch.fft.rfft(exp_w_progression, n=len * 2, dim=0)  # (len+1, dim)
        fft_exp_k = torch.fft.rfft(exp_k, n=len * 2, dim=0)  # (len+1, batch, dim)
        fft_exp_k_v = torch.fft.rfft(exp_k_v, n=len * 2, dim=0)  # (len+1, batch, dim)
```

2023-04-30 05:58 UTC, Geson-anko commented on tests/models/components/test_time_mixing.py
> +    time_mixing.clear_hidden()
```suggestion
    time_mixing.clear_hidden()
    assert time_mixing.numerator_last is None
    assert time_mixing.denominator_last is None
```

2023-04-30 06:03 UTC, myxyy commented on tests/models/components/test_time_mixing.py
> +    time_mixing.clear_hidden()
修正しました  
https://github.com/Geson-anko/RWKV-ReImpl/pull/10/commits/46dca961977b231e7425955e1c93919344e700e2  
https://github.com/Geson-anko/RWKV-ReImpl/pull/10/commits/d3712788f003349d81f1f80ca2001cac93389cdf

2023-05-01 03:49 UTC, Geson-anko approved these changes
OKです。

2023-05-01 03:50 UTC, merged